// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idrrescswdpdaqwzvpoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkcnJlc2Nzd2RwZGFxd3p2cG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTU1NjMsImV4cCI6MjA2NTQ5MTU2M30.Rm1X5jOWQAiMvpg7TId-XcE4U0D06GPAadp5RkN0PzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);